/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizController_getAll"];
        put?: never;
        post: operations["QuizController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizController_getById"];
        put: operations["QuizController_update"];
        post?: never;
        delete: operations["QuizController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        QuestionResponseDto: {
            text: string;
            answers: string[];
            timeLimit?: number;
            id: number;
            quizId: number;
        };
        QuizResponseDto: {
            id: number;
            title: string;
            description?: string;
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            defaultTimeLimit: number;
            questions: components["schemas"]["QuestionResponseDto"][];
            createdAt: string;
            updatedAt: string;
        };
        QuestionDto: {
            text: string;
            answers: string[];
            timeLimit?: number;
        };
        CreateQuizDto: {
            title: string;
            description?: string;
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            defaultTimeLimit: number;
            questions: components["schemas"]["QuestionDto"][];
        };
        UpdateQuizDto: {
            title?: string;
            description?: string;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            defaultTimeLimit?: number;
            questions?: components["schemas"]["QuestionDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    QuizController_getAll: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponseDto"][];
                };
            };
        };
    };
    QuizController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponseDto"];
                };
            };
        };
    };
    QuizController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponseDto"];
                };
            };
        };
    };
    QuizController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponseDto"];
                };
            };
        };
    };
    QuizController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
